import {
    AlertTriangle,
    ArrowRight,
    BarChart,
    Briefcase,
    Check,
    ChevronLeft,
    ChevronRight,
    CircuitBoardIcon,
    Code,
    Command,
    CreditCard,
    File,
    FileKey2,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    LayoutDashboardIcon,
    LifeBuoy,
    Loader2,
    LogIn,
    LogOut,
    LucideIcon,
    LucideShoppingBag,
    Megaphone,
    Moon,
    MoreVertical,
    Paintbrush,
    Pizza,
    Plus,
    ScrollText,
    Settings,
    ShieldCheck,
    SunMedium,
    Trash,
    User,
    UserCircle2Icon,
    UserPen,
    Users,
    Wallet,
    X,
} from 'lucide-react';
  
  export type Icon = LucideIcon;
  
  export const Icons = {

    dashboard: LayoutDashboardIcon,

    // Main Menu
    employee: Users,
    recruitment: Briefcase,
    payroll: Wallet,

    // Department
    marketing: Megaphone,
    designing: Paintbrush,
    development: Code,
    management: BarChart,

    // Settings
    legal: ShieldCheck,
    privacyPolicy: ScrollText,
    termsConditions: FileKey2,
    helpCenter: LifeBuoy,
    logout: LogOut,

    logo: Command,
    login: LogIn,
    close: X,
    product: LucideShoppingBag,
    spinner: Loader2,
    kanban: CircuitBoardIcon,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    post: FileText,
    page: File,
    userPen: UserPen,
    user2: UserCircle2Icon,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    check: Check
  };
  